### ISSUE TITLE
NO issues

### ISSUE THREAD

**Issue by Leo852100** [TongkunGuan/SIGA#6]

**Comment by nishitanand** [comment]
Hi I am getting this error - 'No module named 'ModuleNotFoundError: No module named 'Parallel_test''. I think Parallel_test.py file is missing in the code. I would be grateful if you could provide it!

**Comment by TongkunGuan** [comment]
> Hi I am getting this error - 'No module named 'ModuleNotFoundError: No module named 'Parallel_test''. I think Parallel_test.py file is missing in the code. I would be grateful if you could provide it!

you may need to refer to Parallel_test.py in SIGA_R
