### ISSUE TITLE
Mask for pre-training ViT 

### ISSUE THREAD

**Issue by gaurav-g-12** [TongkunGuan/SIGA#7]
Do we need to provide mask for pre-training ViT base

**Comment by TongkunGuan** [comment]
> Do we need to provide mask for pre-training ViT base

Sorry for the late reply. Can you describe it more specifically?

**Comment by gaurav-g-12** [comment]
Are there any scripts for pertaining the model?

**Comment by TongkunGuan** [comment]
> Do we need to provide mask for pre-training ViT base

yes! You can generate pseudo labels by CCD [https://github.com/TongkunGuan/CCD/tree/main/mask_create].
